
#AccessTOKEN - eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NTFlNzgxMzExNGVkZDQ1OWQ2Y2UxYiIsImlhdCI6MTY5OTg2NjQ5N30.gWm132Li7Q70GxqCqIo-pcjRRyTL_ZBNAAz2XOjX4X0


# POST http://localhost:3000/signin
# Content-Type: application/json

# {
#     "email":"emma@gmail.com",
#     "password":"Emma@123"
# }


POST http://localhost:3000/create-blog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NGY2ODJlMGRiYjIwN2E3NDcyZGU5OSIsImlhdCI6MTY5OTk0MjkwOX0.VGI3wXQnMv_LKQirCILVGRh6_4CD-n-prETLrAjeQ8g

{
    "title":"eko @ 3456 89 ",
    "des":"erg",
    "banner":"ewrtgbgfcvefrgt",
    "content":{
    "blocks":[1,2]
    },
    "tags":["tags1","tags2"]
}
 